### ISSUE TITLE
4月7日的Chrome一键翻墙包MD5码是否有错误？

### ISSUE THREAD

**Issue by pinkchina** [bannedbook/fanqiang#280]
我已通过多个浏览器及迅雷下载Chrome一键翻墙包，下载后MD5值均为6023A1EA85F1357A046A1182288B3D5A，与版主提供的MD5对不上，请核实一下是否是最新版！谢谢！

**Comment by bannedbook** [comment]
是这个 ChromeGo.7z 文件吗，你这个好像是不对啊，文件大小对不对，能不能正常解压？

**Comment by pinkchina** [comment]
文件大小好像差不多，能解压，就是md5总是对不上！

**Comment by bannedbook** [comment]
最新版是这个 e52c5843a75bafbd081a9b3a767db75d ，文件大小：102,921,740 字节 文件日期，2018.4.3日

**Comment by bannedbook** [comment]
稍等，我再看看

**Comment by bannedbook** [comment]
你的是对的，是我写错了，抱歉

**Comment by bannedbook** [comment]
是因为服务器缓存了旧的版本，现在重新下载一下应该就对了。谢谢您的反馈

**Comment by pinkchina** [comment]
应该多谢您，感谢您的无私奉献！

**Comment by qianfanglei** [comment]
现在都不太好用了，可以推荐你较为稳定的翻墙办法，一年一百多一些发自我的iPhone------------------ 原始邮件 ------------------发件人: cxfdyc  <notifications@github.com>发送时间: 2018年5月9日 10:22收件人: bannedbook/fanqiang <fanqiang@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[bannedbook/fanqiang] 4月7日的Chrome一键翻墙包MD5码是否有错误？ (#280)我是新手 。软件从哪里下？谢谢

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bannedbook/fanqiang","title":"bannedbook/fanqiang","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bannedbook/fanqiang"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cxfdyc in #280: 我是新手 。软件从哪里下？谢谢"}],"action":{"name":"View Issue","url":"https://github.com/bannedbook/fanqiang/issues/280#issuecomment-387600054"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [bannedbook/fanqiang] 4月7日的Chrome一键翻墙包MD5码是否有错误？ (#280)","sections":[{"text":"","activityTitle":"**cxfdyc**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@cxfdyc","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"bannedbook/fanqiang\",\"issueId\":280,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"bannedbook/fanqiang\",\"issueId\":280}"},{"targets":[{"os":"default","uri":"https://github.com/bannedbook/fanqiang/issues/280#issuecomment-387600054"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":323754668}"}],"themeColor":"26292E"}

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85

**Comment by cxfdyc** [comment]
谢谢！我用港版手机，已安装chrome，可以下载使用吗？小白，一点不懂。下了个gohosts，不稳定

**Comment by bannedbook** [comment]
手机试试看 这里
https://github.com/bannedbook/fanqiang/wiki/%E5%AE%89%E5%8D%93%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6
