### ISSUE TITLE
google账号

### ISSUE THREAD

**Issue by biubiuw** [bannedbook/fanqiang#382]
怎么创建Google账号呀？用Goflyway，Brook，蓝灯，Firefly都是卡在验证电话号码那一步，还有其他办法吗？赐教~

**Comment by bannedbook** [comment]
可能是需要 输入一个电话号码 来验证吧

**Comment by Baiyebuhao** [comment]
现在需要电话认证了吗？






------------------ 原始邮件 ------------------
发件人: "biubiuw"<notifications@github.com>; 
发送时间: 2019年7月18日(星期四) 下午2:42
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [bannedbook/fanqiang] google账号 (#382)




怎么创建Google账号呀？用Goflyway，Brook，蓝灯，Firefly都是卡在验证电话号码那一步，还有其他办法吗？赐教~
 
&mdash;

**Comment by biubiuw** [comment]
> 现在需要电话认证了吗？
> [...](#)
> ------------------原始邮件------------------发件人：“biubiuw”<notifications @ github。 COM>; 发送时间：2019年7月18日（星期四）下午2:42收件人：“bannedbook / fanqiang”<fanqiang@noreply.github.com>; 抄送：“已订阅”<subscribed@noreply.github.com>; 主题：[bannedbook / fanqiang] google账号（[＃382](https://github.com/bannedbook/fanqiang/issues/382)）怎么创建Google账号呀？用Goflyway，Brook，蓝灯，Firefly都是卡在验证电话号码那一步，还有其他办法吗？赐教〜＆mdash; 您收到此消息是因为您订阅了此主题。直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by biubiuw** [comment]
我尝试的都要😂而且中国号码说不能验证～发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：Baiyebuhao 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 现在需要电话认证了吗？



























------------------ 原始邮件 ------------------



发件人: "biubiuw"<notifications@github.com>; 



发送时间: 2019年7月18日(星期四) 下午2:42



收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>; 



抄送: "Subscribed"<subscribed@noreply.github.com>; 



主题: [bannedbook/fanqiang] google账号 (#382)



















怎么创建Google账号呀？用Goflyway，Brook，蓝灯，Firefly都是卡在验证电话号码那一步，还有其他办法吗？赐教~



 



&mdash;

**Comment by Baiyebuhao** [comment]
我替你感到悲伤，幸好我之前注册了几个账号


 
---原始邮件---
发件人: "biubiuw"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 中午11:09
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;
主题: Re: [bannedbook/fanqiang] google账号 (#382)


我尝试的都要😂而且中国号码说不能验证～发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：Baiyebuhao 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 现在需要电话认证了吗？ 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 发件人: "biubiuw"<notifications@github.com>;  
 
 发送时间: 2019年7月18日(星期四) 下午2:42 
 
 收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;  
 
 抄送: "Subscribed"<subscribed@noreply.github.com>;  
 
 主题: [bannedbook/fanqiang] google账号 (#382) 
 
 
 
 
 
 
 
 
 
 怎么创建Google账号呀？用Goflyway，Brook，蓝灯，Firefly都是卡在验证电话号码那一步，还有其他办法吗？赐教~ 
 
   
 
 &mdash;

**Comment by Baiyebuhao** [comment]
你还可以买张实体卡，不过现在的实体卡都需要月租了

---原始邮件---
发件人: "biubiuw"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 中午11:09
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;
主题: Re: [bannedbook/fanqiang] google账号 (#382)


我尝试的都要&#x1F602;而且中国号码说不能验证～发自我的华为手机-------- 原始邮&#x4EF6; --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发&#x4EF6;人：Baiyebuhao 收&#x4EF6;人：bannedbook/fanqiang 抄送：biubiuw ,Author 现在需要电话认证了吗？ 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 
 发&#x4EF6;人: "biubiuw"<notifications@github.com>;  
 
 发送时间: 2019年7月18日(星期四) 下午2:42 
 
 收&#x4EF6;人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;  
 
 抄送: "Subscribed"<subscribed@noreply.github.com>;  
 
 主题: [bannedbook/fanqiang] google账号 (#382) 
 
 
 
 
 
 
 
 
 
 怎么创建Google账号呀？用Goflyway，Brook，蓝灯，Firefly都是卡在验证电话号码那一步，还有其他办法吗？赐教~ 
 
   
 
 &mdash; 
 
 You are receiving this because you are subscribed to this thread. 
 
 Reply to this email directly, view it on GitHub, or mute the thread. 
 
 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by biubiuw** [comment]
中国号码不能验证是怎么回事呀? 你们的都可以么？😂😂有大佬知道咋办吗？发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：如何翻墙 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧

**Comment by Baiyebuhao** [comment]
我没用中国号码，之前不用号码就可以注册

---原始邮件---
发件人: "biubiuw"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 中午11:13
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;
主题: Re: [bannedbook/fanqiang] google账号 (#382)


中国号码不能验证是怎么回事呀? 你们的都可以么？&#x1F602;&#x1F602;有大佬知道咋办吗？发自我的华为手机-------- 原始邮&#x4EF6; --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发&#x4EF6;人：如何翻墙 收&#x4EF6;人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧 
 
 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by Baiyebuhao** [comment]
你用这个链接试试，https://accounts.google.com/signup/v2/webcreateaccount?service=grandcentral&continue=https%3A%2F%2Fvoice.google.com%2F&hl=zh-HK&flowName=GlifWebSignIn&flowEntry=SignUp


 
---原始邮件---
发件人: "biubiuw"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 中午11:13
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;
主题: Re: [bannedbook/fanqiang] google账号 (#382)


中国号码不能验证是怎么回事呀? 你们的都可以么？😂😂有大佬知道咋办吗？发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：如何翻墙 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧

**Comment by biubiuw** [comment]
-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：Baiyebuhao 收件人：bannedbook/fanqiang 抄送：biubiuw ,State change 你用这个链接试试，https://accounts.google.com/signup/v2/webcreateaccount?service=grandcentral&continue=https%3A%2F%2Fvoice.google.com%2F&hl=zh-HK&flowName=GlifWebSignIn&flowEntry=SignUp











 



---原始邮件---



发件人: "biubiuw"<notifications@github.com>



发送时间: 2019年7月19日(星期五) 中午11:13



收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;



抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;



主题: Re: [bannedbook/fanqiang] google账号 (#382)











中国号码不能验证是怎么回事呀? 你们的都可以么？😂😂有大佬知道咋办吗？发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：如何翻墙 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧

**Comment by biubiuw** [comment]
谢啦😄发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：Baiyebuhao 收件人：bannedbook/fanqiang 抄送：biubiuw ,State change 你用这个链接试试，https://accounts.google.com/signup/v2/webcreateaccount?service=grandcentral&continue=https%3A%2F%2Fvoice.google.com%2F&hl=zh-HK&flowName=GlifWebSignIn&flowEntry=SignUp











 



---原始邮件---



发件人: "biubiuw"<notifications@github.com>



发送时间: 2019年7月19日(星期五) 中午11:13



收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;



抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;



主题: Re: [bannedbook/fanqiang] google账号 (#382)











中国号码不能验证是怎么回事呀? 你们的都可以么？😂😂有大佬知道咋办吗？发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：如何翻墙 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧

**Comment by Baiyebuhao** [comment]
你成功了吗？反正我试了可以


 
---原始邮件---
发件人: "biubiuw"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 中午1:16
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;
主题: Re: [bannedbook/fanqiang] google账号 (#382)


谢啦😄发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：Baiyebuhao 收件人：bannedbook/fanqiang 抄送：biubiuw ,State change 你用这个链接试试，https://accounts.google.com/signup/v2/webcreateaccount?service=grandcentral&continue=https%3A%2F%2Fvoice.google.com%2F&hl=zh-HK&flowName=GlifWebSignIn&flowEntry=SignUp 
 
 
 
 
 
   
 
 ---原始邮件--- 
 
 发件人: "biubiuw"<notifications@github.com> 
 
 发送时间: 2019年7月19日(星期五) 中午11:13 
 
 收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>; 
 
 抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>; 
 
 主题: Re: [bannedbook/fanqiang] google账号 (#382) 
 
 
 
 
 
 中国号码不能验证是怎么回事呀? 你们的都可以么？😂😂有大佬知道咋办吗？发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：如何翻墙 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧

**Comment by biubiuw** [comment]
我不行啊😂何解～还是说我号码不能用于验证，感觉我操作没问题呀😭发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：Baiyebuhao 收件人：bannedbook/fanqiang 抄送：biubiuw ,State change 你成功了吗？反正我试了可以











 



---原始邮件---



发件人: "biubiuw"<notifications@github.com>



发送时间: 2019年7月19日(星期五) 中午1:16



收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;



抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;



主题: Re: [bannedbook/fanqiang] google账号 (#382)











谢啦😄发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：Baiyebuhao 收件人：bannedbook/fanqiang 抄送：biubiuw ,State change 你用这个链接试试，https://accounts.google.com/signup/v2/webcreateaccount?service=grandcentral&continue=https%3A%2F%2Fvoice.google.com%2F&hl=zh-HK&flowName=GlifWebSignIn&flowEntry=SignUp 



 



 



 



 



 



   



 



 ---原始邮件--- 



 



 发件人: "biubiuw"<notifications@github.com> 



 



 发送时间: 2019年7月19日(星期五) 中午11:13 



 



 收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>; 



 



 抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>; 



 



 主题: Re: [bannedbook/fanqiang] google账号 (#382) 



 



 



 



 



 



 中国号码不能验证是怎么回事呀? 你们的都可以么？😂😂有大佬知道咋办吗？发自我的华为手机-------- 原始邮件 --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发件人：如何翻墙 收件人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧

**Comment by Baiyebuhao** [comment]
你加我QQ啊

---原始邮件---
发件人: "biubiuw"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 下午2:42
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;
主题: Re: [bannedbook/fanqiang] google账号 (#382)


我不行啊&#x1F602;何解～还是说我号码不能用于验证，感觉我操作没问题呀&#x1F62D;发自我的华为手机-------- 原始邮&#x4EF6; --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发&#x4EF6;人：Baiyebuhao 收&#x4EF6;人：bannedbook/fanqiang 抄送：biubiuw ,State change 你成功了吗？反正我试了可以 
 
 
 
 
 
   
 
 ---原始邮&#x4EF6;--- 
 
 发&#x4EF6;人: "biubiuw"<notifications@github.com> 
 
 发送时间: 2019年7月19日(星期五) 中午1:16 
 
 收&#x4EF6;人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>; 
 
 抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>; 
 
 主题: Re: [bannedbook/fanqiang] google账号 (#382) 
 
 
 
 
 
 谢啦&#x1F604;发自我的华为手机-------- 原始邮&#x4EF6; --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发&#x4EF6;人：Baiyebuhao 收&#x4EF6;人：bannedbook/fanqiang 抄送：biubiuw ,State change 你用这个链接试试，https://accounts.google.com/signup/v2/webcreateaccount?service=grandcentral&continue=https%3A%2F%2Fvoice.google.com%2F&hl=zh-HK&flowName=GlifWebSignIn&flowEntry=SignUp  
 
   
 
   
 
   
 
   
 
   
 
     
 
   
 
  ---原始邮&#x4EF6;---  
 
   
 
  发&#x4EF6;人: "biubiuw"<notifications@github.com>  
 
   
 
  发送时间: 2019年7月19日(星期五) 中午11:13  
 
   
 
  收&#x4EF6;人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>;  
 
   
 
  抄送: "Comment"<comment@noreply.github.com>;"Baiyebuhao"<617212419@qq.com>;  
 
   
 
  主题: Re: [bannedbook/fanqiang] google账号 (#382)  
 
   
 
   
 
   
 
   
 
   
 
  中国号码不能验证是怎么回事呀? 你们的都可以么？&#x1F602;&#x1F602;有大佬知道咋办吗？发自我的华为手机-------- 原始邮&#x4EF6; --------主题：Re: [bannedbook/fanqiang] google账号 (#382)发&#x4EF6;人：如何翻墙 收&#x4EF6;人：bannedbook/fanqiang 抄送：biubiuw ,Author 可能是需要 输入一个电话号码 来验证吧   
 
   
 
     
 
   
 
   —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   
 
   
 
  —  
 
   
 
  You are receiving this because you commented.  
 
   
 
  Reply to this email directly, view it on GitHub, or mute the thread.  
 
   
 
  —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.  
 
 — 
 
 You are receiving this because you commented. 
 
 Reply to this email directly, view it on GitHub, or mute the thread. 
 
 —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by Baiyebuhao** [comment]
我试过，有些中国号码可以注册
